apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
  namespace: argocd
spec:
  replicas: 0
  sources:
    - repoURL: https://helm.irsigler.cloud
      chart: uptime-kuma
      targetRevision: 2.14.2
      helm:
        valueFiles:
          - $values/02_UPTIME/values.yaml
    - repoURL: "https://github.com/Jarne-Theys/deployment-exercises-Tiebevn"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: uptime
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
