apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine
  namespace: argocd
spec:
  sources:
      - repoUrl: 


      helm:
        valueFiles:
          - $values/03_REDMINE/values.yaml
    - repoURL: "https://github.com/Jarne-Theys/deployment-exercises-Tiebevn"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redmine
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
